Terraform 1
Otus-DevOps-2019-08/sanek32ru_infra pull request #5
Opened 2019-10-10 20:18 UTC by sanek32ru

# Выполнено ДЗ №6

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Установлен terraform
 - Инфраструктура описана и развернута с помощью файлов-описаний terraform

## Как запустить проект:
 - Преобразовать terraform.tfvars.example в terraform.tfvars
 - Сделать terraform apply

## Как проверить работоспособность:
 - Перейти по ссылке http://35.195.86.212:9292/

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2019-10-10 20:52 UTC, sanek32ru commented
Не пойму в чем ошибка билда:
 ×  Command: `cd terraform && tflint --var-file=terraform.tfvars.example --error-with-issues` stdout should match "Your code is following the best practices"
     expected "" to match "Your code is following the best practices"
     ×  Command: `cd terraform && tflint --var-file=terraform.tfvars.example --error-with-issues` stderr should eq ""
     
     expected: ""
          got: "Failed to parse CLI options. An error occurred:\n\nError: `error-with-issues` option was removed in v0.9.0. The behavior is now default\n\n"
     
     (compared using ==)
     
     Diff:
     @@ -1 +1,4 @@
     +Failed to parse CLI options. An error occurred:
     +
     +Error: `error-with-issues` option was removed in v0.9.0. The behavior is now default
     ×  Command: `cd terraform && tflint --var-file=terraform.tfvars.example --error-with-issues` exit_status should eq 0
     
     expected: 0
          got: 2
     
     (compared using ==)

2019-10-11 08:23 UTC, Ctacfs commented
В файле .travis.yml нужно исправить версию скрипта проверки дз на версию текущего потока.
Сейчас там
`https://raw.githubusercontent.com/express42/otus-homeworks/2019-05/run.sh`
А должно быть
`https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh`

2019-10-12 09:50 UTC, mrgreyves requested changes
Здравствуйте!) Там ошибочка закралась к вам. Дополнительная информация в комментарии. Пока возвращаю на доработку.

2019-10-12 15:44 UTC, mrgreyves approved these changes
Здравствуйте!) Хорошо что исправили ошибку. ДЗ принимаю!=)

2019-10-12 15:51 UTC, merged